file:
  path: 'log\\'
  volume_train: "./data/sagan_pre/bike_volume_train.npy"
  flow_train: "./data/sagan_pre/bike_flow_train.npy"
  weather_train: "./data/sagan_pre/weather_train.npy"
  volume_test: "./data/sagan_pre/bike_volume_test.npy"
  flow_test: "./data/sagan_pre/bike_flow_test.npy"
  weather_test: "./data/sagan_pre/weather_test.npy"
  poi_data: "./data/sagan_pre/bike_poi.npy"
training:
  # size of batch
  batch_size: 64
  # maximum epochs
  max_epochs: 80
dataset: 
  # num of day for attention (value P in paper)
  att_lstm_num: 3
  # num of time for attention (value Q in paper)
  long_term_lstm_seq_len: 3
  # length of short tern value
  short_term_lstm_seq_len: 7
  # neighbors for local cnn (2*cnn_nbhd_size+1) for area size
  cnn_nbhd_size: 3
  # for feature extraction
  nbhd_size: 2
  # dimension of local conv output
  cnn_flat_size: 128
  threshold: 10
  # not sure
  volume_train_max: 299.0
  volume_test_max: 307.0
  flow_train_max: 61.0
  flow_test_max: 59.0
  timeslot_sec: 1800
  hist_feature_daynum: 7
  last_feature_num: 48
  # training data time
  # date: (start)~(end-1), hour: (start)~(end-1)
  # current date: 0 ~ 123
  # current time: 0 ~ 48
  start_date_train: 0
  end_date_train: 123
  start_hour_train: 0
  end_hour_train: 48
  # testing data time
  # date: (start)~(end-1), hour: (start)~(end-1)
  # current date: 0 ~ 30
  # current time: 0 ~ 48
  start_date_test: 0
  end_date_test: 30
  start_hour_test: 0
  end_hour_test: 48
searching:
  generation_num: 30
  population_num: 15
  annealing_ratio: 0.9
  initial_tmp: 200
  final_tmp: 1
  crossover_rate: 0.8
  annealing_prob: 1
model:
  num_choice: 3
  num_layers: 6